name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Desplegar Edge Function 'crear-admin'
        run: supabase functions deploy crear-admin --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}